name: Documentation

on:
  push:
    branches: [ "main"]


jobs:
  pages:
    runs-on: ubuntu-20.04
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
    
    - id: checkout_repo_deps
      uses: actions/checkout@v4
      with:
        sparse-checkout: |
          pyproject.toml
          
    - id: setup_python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12' 
        
    - id: install_deps
      run: pip install poetry && poetry install --with dev
      
    - id: deployment
      uses: sphinx-notes/pages@v3
      with:
        documentation_path: ./docs
