name: Documentation

on:
  push:
    branches: [ "main", "gh_pages"]

  deploy:
  runs-on: ubuntu-latest
  needs: build  # Ensure that the build job is completed before deploying
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    - name: Setup Pages
      uses: actions/configure-pages@v5
    - name: Upload Documentation Artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: './docs/_build/html/*'  # Path to the built HTML documentation
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4